
services:
  apache:
    image: httpd:latest
    container_name: apache-server
    ports:
      - "8080:80"
    volumes:
      - "/home/andreas/Documents/Github/open-cp/templates:/usr/local/apache2/htdocs/"
    restart: unless-stopped
